### ISSUE TITLE
the relation numbers

### ISSUE THREAD

**Issue by jing86736238** [seq-to-mind/DMRST_Parser#2]
hello, i just want to know the relation nums , because i find the relations nums in your paper is 18, but i just find 16 in your references, the 2 is span and same-unit?

**Comment by seq-to-mind** [comment]
You can see the current complete relation label list in the file `1_MUL_generate_input_pkl_XLMR.py`.
This label list is built on the multi-lingual RST corpora we used (and described in the paper).
