### ISSUE TITLE
preprocessing rs3

### ISSUE THREAD

**Issue by metabolean5** [seq-to-mind/DMRST_Parser#6]
Hi again,

I would like to fine-tune  your model using some of my own data.

To preprocess my corpora i should use 

bash path_to/preprocess_rst/code/read_corpus.sh PATH_TO_SRC_DIR PATH_TO_INPUT_DATA PATH_TO_OUTPUT_DATA

Can my data be in the .rs3 format for this part ? (i'd like to know which conversion scripts to code)

Thank you

**Comment by seq-to-mind** [comment]
Yes the data can be in .rs3 format. Kindly see the following readme file for more details:
https://github.com/seq-to-mind/DMRST_Parser/tree/main/Preprocess_RST_Data/1_uniform_treebanks#readme

**Comment by metabolean5** [comment]
Thank you for the response.
Do you have any tools or scripts which convert between rs3 and the top-down constituency format? 

Also, In some of the data I generated I have had trouble finding examples of multi-nuclear relations (joints for instance) which have more than 2 nuclei. Can the parser possibly produce triple or quadruple nucleus relations ?

**Comment by seq-to-mind** [comment]
For rs3 conversion, you can run code here and following the Readme file for details.
https://github.com/seq-to-mind/DMRST_Parser/tree/main/Preprocess_RST_Data/1_uniform_treebanks/code
https://github.com/seq-to-mind/DMRST_Parser/tree/main/Preprocess_RST_Data/1_uniform_treebanks#readme

Multi-nuclear relations can be converted to binary nodes, for instance, the joints can be presented in "nuclear - nuclear".

**Comment by metabolean5** [comment]
Thank you, 
You can consider this issue closed.
