### ISSUE TITLE
training 

### ISSUE THREAD

**Issue by metabolean5** [seq-to-mind/DMRST_Parser#7]
Hi, I am training your parser on some of my own gold data.

Very early in the training process I stumble upon this error,

`

14.115264892578125 4.056464672088623 3.5880379676818848
lambda: 1.036903940338129 0.8700457499187157 1.0930503097431552
epoch:0, iteration:25
0.7924186587333679 2.4157767295837402 3.287290573120117
lambda: 0.8786966479131265 1.0319364060934593 1.0893669459934139
epoch:0, iteration:30
4.340151786804199 4.182605743408203 3.5921711921691895
lambda: 0.9947851916184731 0.8553527256977879 1.149862082683739
epoch:0, iteration:35
2.764946222305298 7.070889949798584 3.2582828998565674
lambda: 0.9115995262586944 1.0049451353749437 1.083455338366362
epoch:0, iteration:40
1.6766210794448853 3.334477663040161 3.493067979812622
lambda: 0.6487871661038682 1.348979856622742 1.0022329772733896
Traceback (most recent call last):
  File "/vol/tensusers/mpdev/DMRST_Parser/MUL_main_Train.py", line 203, in <module>
    best_R_nuclearity = TrainingProcess.train()
  File "/vol/tensusers/mpadev/DMRST_Parser/Training.py", line 353, in train
    total_r = math.exp(r_label / dwa_T) + math.exp(r_tree / dwa_T) + math.exp(r_edu / dwa_T)
OverflowError: math range error

`

Any idea what might cause it ? Is there a way to bypass it ?

**Comment by seq-to-mind** [comment]
You can print out the values of r_label, r_edu, r_tree, and daw_T to debug at the example with excetpion.
This error may come from invalid data point, or anomalous values.

**Comment by metabolean5** [comment]
some values do indeed get too high, though it is not linked to certain data points because similar trees seen before in the training process do not cause such high values.

I am currently doing some filtering and things seem to run ok. Thank you

Though now my values are now all nan after epoch 3 iteration 180:

epoch:3, iteration:180
nan nan nan
lambda: nan nan nan

I have experimented with different training sets and epoch 3 seems to be when the values turn to nan.

Any idea why this happens ?

**Comment by seq-to-mind** [comment]
Maybe you can try set this training parameter as False, to see whether the problem solved.
https://github.com/seq-to-mind/DMRST_Parser/blob/231d8c0d28ba8cba074e29a6ff99e858e4742735/config.py#L24

**Comment by seq-to-mind** [comment]
If you found that changing that config parameter works, can leave a comment here.
If no further questions, will close this first.

**Comment by metabolean5** [comment]
I ending up clipping the values.
Thank you for your help!
